import type { Metadata } from 'next';

import { inter } from '@/app/ui/fonts';
import './globals.css';
import TopNav from '@/app/ui/home/topnav';
import { useState } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [clicked, setClicked] = useState(false);

  // const toggleMenu = () => {
  //   setClicked(!clicked);
  // };

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div>
          <TopNav />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
